// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkfgsrgwrssyznsaniat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZmdzcmd3cnNzeXpuc2FuaWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDg4MjgsImV4cCI6MjA1OTY4NDgyOH0.Hm56t9ZaYq0m4rGts77-u1K5GE7pdYcGUrOH74sqoX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);